logging:
  level:
    org.springframework: debug

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cinema
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
